Candy monitoring stack
ConnorBarnes88/indy-node-monitor pull request #1
Opened 2022-03-23 18:33 UTC by PatStLouis

- Syntax correction in manage script
- Fix api path url in telegraph config file
- Configuration changes to monitor Candy-dev network

2022-06-23 19:28 UTC, PatStLouis commented on telegraf/telegraf.conf
> +  urls = ["http://influxdb:8086/api/v2"]
```suggestion
  urls = ["http://influxdb:8086"]
```

2022-11-07 22:20 UTC, WadeBarnes requested changes
Some small changes to make.

2022-11-07 22:20 UTC, WadeBarnes commented on manage
> +DOCKER_COMPOSE_EXE="${DOCKER_EXE}-compose"
This change should be reverted.  `docker-compose` is deprecated.

2022-11-07 22:20 UTC, WadeBarnes commented on telegraf/telegraf.conf
> +  urls = ["http://influxdb:8086/api/v2"]
This seems to be incompatible with InfluxDB v1.8.  It breaks all of the existing controls trying to access the InfluxDB data sources.  This should be combined with a complete project update to InfluxDB v2.x.

2022-11-07 22:20 UTC, WadeBarnes commented on telegraf/telegraf.conf
> +  [[inputs.http]]
Remove leading whitespace.

2022-11-07 22:20 UTC, WadeBarnes commented on fetch-validator-status/networks.json
> +  },
The `main` branch has updated the network list.  I'll be rebasing the `monitoring-stack` branch on it.

2022-11-07 22:20 UTC, WadeBarnes commented on telegraf/telegraf.conf
> +[[inputs.http]]
This is find.  The network code for the CANdy-Dev network will still be `cdn`.

2022-11-07 22:46 UTC, WadeBarnes commented
@PatStLouis, I've rebased the `monitoring-stack` branch on the latest from the Hyperledger `main` branch.  You should rebase your PR on the updates, and make the changes I've suggested above.  Then I can merge the changes and get it all merged into the Hyperledger  `monitoring-stack` branch.

2022-11-08 14:16 UTC, PatStLouis commented
Thanks for the thorough review @WadeBarnes I will take actions and get back to you when the PR is ready.

2023-03-16 18:38 UTC, closed without merging